# Generated by Django 5.2.8 on 2025-12-03 23:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('Actor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Biography', models.TextField(blank=True)),
                ('Picture', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Birth_date', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('Director_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Biography', models.TextField(blank=True, null=True)),
                ('Picture', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Birth_date', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True)),
                ('Poster', models.BinaryField(blank=True, max_length='max', null=True)),
                ('Trailer', models.FileField(blank=True, null=True, upload_to='trailers/')),
                ('MovieDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to='Movie.director')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('Image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ImageFile', models.FileField(blank=True, null=True, upload_to='imagegallery/')),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagegallery', to='Movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='FilmCritic',
            fields=[
                ('Filmcritic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Critic Name')),
                ('Biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('Organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organization/Media')),
                ('RatingScale', models.IntegerField(blank=True, default=10, null=True, verbose_name='Rating Scale')),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('Movie', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='Movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('MovieActor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, default='Unknown')),
                ('role', models.CharField(default='Unknown', max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actors', to='Movie.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movies', to='Movie.movie')),
            ],
            options={
                'unique_together': {('movie', 'actor')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='MovieActor',
            field=models.ManyToManyField(through='Movie.MovieActor', to='Movie.actor'),
        ),
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('Music_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Cover', models.BinaryField(blank=True, max_length='max', null=True)),
                ('MusicFile', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('Artist', models.CharField(blank=True, max_length=200, null=True)),
                ('Duration', models.DurationField(blank=True, null=True)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Songs', to='Movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosofTheActors',
            fields=[
                ('Image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ImageFile', models.FileField(blank=True, null=True, upload_to='imagegallery/')),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagegallery', to='Movie.actor')),
            ],
        ),
    ]
