# Generated by Django 5.2.8 on 2025-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_movie_imdbscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.CharField(blank=True, choices=[('Ac', 'Action'), ('Ad', 'Adventure'), ('An', 'Animation'), ('Co', 'Comedy'), ('Cr', 'Crime'), ('Do', 'Documentary'), ('Dr', 'Drama'), ('Fa', 'Fantasy'), ('Hi', 'Historical / Biopic'), ('Ho', 'Horror'), ('Mu', 'Musical'), ('My', 'Mystery'), ('Ro', 'Romance'), ('Sc', 'Science Fiction (Sci-Fi)'), ('Th', 'Thriller'), ('Wa', 'War')], max_length=2),
        ),
    ]
